# Generated by Django 4.2.1 on 2023-05-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_alter_blogger_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='password',
            field=models.SlugField(max_length=30),
        ),
    ]
