# Generated by Django 4.2.1 on 2023-05-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_alter_uploadedblogs_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedblogs',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedblogs',
            name='likes',
            field=models.ImageField(blank=True, default=0, upload_to=''),
        ),
    ]
