# Generated by Django 4.2.1 on 2023-05-20 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_uploadedblogs_comments_uploadedblogs_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedblogs',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.blogger'),
        ),
    ]
