# Generated by Django 4.2.1 on 2023-05-22 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0011_remove_uploadedblogs_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.uploadedblogs'),
        ),
        migrations.AddField(
            model_name='likes',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.uploadedblogs'),
        ),
    ]
