# Generated by Django 4.2.1 on 2023-05-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0013_alter_uploadedblogs_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
