# Generated by Django 4.2.1 on 2023-05-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0014_likes_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='likes',
            new_name='count',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='user',
        ),
        migrations.AlterField(
            model_name='comments',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
