# Generated by Django 4.2.1 on 2023-05-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0016_uploadedblogs_likes_delete_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedblogs',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='Blog.blogger'),
        ),
    ]
