# Generated by Django 4.2.1 on 2023-05-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0017_alter_uploadedblogs_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='username',
            field=models.CharField(default='anonymous', max_length=50),
        ),
    ]
