# Generated by Django 4.2.1 on 2023-05-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0018_comments_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedblogs',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
