# Generated by Django 4.2.1 on 2023-05-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_remove_customuser_birth_year_customuser_birthyear_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
